apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: keda-hpa-wordpress
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wordpress
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 10
